export const defaultPermissions = {
  manualTimeTracking: true,
  cameraAttendance: false,
  locationRequired: false,
  faceVerification: false,
  timeIn: true,
  breakIn: true,
  breakOut: true,
  timeOut: true,
  paidBreakOption: true,
  unpaidBreakOption: true,
  requireBreakReason: false,
  employeeComments: true,
  correctionRequests: true,
  employeePdfExport: true,
  salaryEstimate: true,
  leaveRequests: true,
  restDayStatus: true,
  announcements: true,
};
